version: '2'
services:
  hlavja-tictactoe-backend:
    image: pia/hlavja-tictactoe-backend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hlavja-tictactoe-postgresql:5432/TicTacToe
      - SPRING_DATASOURCE_USERNAME=TicTacToe
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    ports:
      - 8080:8080
